"""add tipo to conteudo unique constraint

Revision ID: 0ff303d2a2b8
Revises: 7d4080ecbdd6
Create Date: 2026-09-22 05:13:38.168811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff303d2a2b8'
down_revision: Union[str, Sequence[str], None] = '7d4080ecbdd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_conteudo_id_externo_api_fonte'), table_name='conteudo')
    op.create_unique_constraint('uq_conteudo_id_externo_api_fonte_tipo', 'conteudo', ['id_externo', 'api_fonte', 'tipo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_conteudo_id_externo_api_fonte_tipo', 'conteudo', type_='unique')
    op.create_index(op.f('uq_conteudo_id_externo_api_fonte'), 'conteudo', ['id_externo', 'api_fonte'], unique=True)
    # ### end Alembic commands ###
