"""create filme and serie tables

Revision ID: 18cb130b180c
Revises: 83941b441930
Create Date: 2026-09-19 11:59:03.018743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '18cb130b180c'
down_revision: Union[str, Sequence[str], None] = '83941b441930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conteudo', 'api_fonte',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('kitsu', 'tmdb', name='api_fonte_enum'),
               existing_nullable=False)
    op.alter_column('conteudo', 'tipo',
               existing_type=mysql.ENUM('Anime', 'Filme', 'Série'),
               type_=sa.Enum('anime', 'filme', 'serie', name='tipo_conteudo_enum'),
               existing_nullable=False)
    op.drop_index(op.f('id_externo'), table_name='conteudo')
    op.create_unique_constraint('uq_conteudo_id_externo_api_fonte', 'conteudo', ['id_externo', 'api_fonte'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_conteudo_id_externo_api_fonte', 'conteudo', type_='unique')
    op.create_index(op.f('id_externo'), 'conteudo', ['id_externo', 'api_fonte'], unique=True)
    op.alter_column('conteudo', 'tipo',
               existing_type=sa.Enum('anime', 'filme', 'serie', name='tipo_conteudo_enum'),
               type_=mysql.ENUM('Anime', 'Filme', 'Série'),
               existing_nullable=False)
    op.alter_column('conteudo', 'api_fonte',
               existing_type=sa.Enum('kitsu', 'tmdb', name='api_fonte_enum'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
