"""add unique constraint to conteudo_id and usuario_id on favorito and assistido

Revision ID: 1d7ce2e5b3be
Revises: 0ff303d2a2b8
Create Date: 2026-09-23 23:31:38.117549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d7ce2e5b3be'
down_revision: Union[str, Sequence[str], None] = '0ff303d2a2b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_conteudo_id_usuario_id', 'assistido', ['conteudo_id', 'usuario_id'])
    op.create_unique_constraint('uq_conteudo_id_usuario_id', 'favorito', ['conteudo_id', 'usuario_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_conteudo_id_usuario_id', 'favorito', type_='unique')
    op.drop_constraint('uq_conteudo_id_usuario_id', 'assistido', type_='unique')
    # ### end Alembic commands ###
