"""create_filme_and_serie_tables

Revision ID: 7d4080ecbdd6
Revises: 83941b441930
Create Date: 2026-09-19 14:36:57.358263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7d4080ecbdd6'
down_revision: Union[str, Sequence[str], None] = '83941b441930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filme',
    sa.Column('conteudo_id', sa.BigInteger(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('titulo_original', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('capa', sa.String(length=255), nullable=True),
    sa.Column('banner', sa.String(length=255), nullable=True),
    sa.Column('data_lancamento', sa.Date(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conteudo_id'], ['conteudo.id'], ),
    sa.PrimaryKeyConstraint('conteudo_id')
    )
    op.create_table('serie',
    sa.Column('conteudo_id', sa.BigInteger(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('titulo_original', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('capa', sa.String(length=255), nullable=True),
    sa.Column('banner', sa.String(length=255), nullable=True),
    sa.Column('data_lancamento', sa.Date(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conteudo_id'], ['conteudo.id'], ),
    sa.PrimaryKeyConstraint('conteudo_id')
    )
    op.alter_column('conteudo', 'api_fonte',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('kitsu', 'tmdb', name='api_fonte_enum'),
               existing_nullable=False)
    op.alter_column('conteudo', 'tipo',
               existing_type=mysql.ENUM('ANIME', 'FILME', 'SERIE'),
               type_=sa.Enum('anime', 'filme', 'serie', name='tipo_conteudo_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conteudo', 'tipo',
               existing_type=sa.Enum('anime', 'filme', 'serie', name='tipo_conteudo_enum'),
               type_=mysql.ENUM('ANIME', 'FILME', 'SERIE'),
               existing_nullable=False)
    op.alter_column('conteudo', 'api_fonte',
               existing_type=sa.Enum('kitsu', 'tmdb', name='api_fonte_enum'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_table('serie')
    op.drop_table('filme')
    # ### end Alembic commands ###
