"""versao 1

Revision ID: 83941b441930
Revises: 
Create Date: 2026-08-17 07:54:36.547297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83941b441930'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conteudo',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_externo', sa.BigInteger(), nullable=False),
    sa.Column('api_fonte', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('ANIME', 'FILME', 'SERIE', name='tipoconteudo'), nullable=False),
    sa.Column('data_adicao', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_externo', 'api_fonte', name='uq_conteudo_id_externo_api_fonte')
    )
    op.create_table('usuario',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('foto_perfil_path', sa.String(length=255), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('assistido',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conteudo_id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('data_adicao', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conteudo_id'], ['conteudo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliacao',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('conteudo_id', sa.BigInteger(), nullable=False),
    sa.Column('estrelas', sa.DECIMAL(precision=2, scale=1), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conteudo_id'], ['conteudo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorito',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conteudo_id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('data_adicao', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conteudo_id'], ['conteudo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorito')
    op.drop_table('avaliacao')
    op.drop_table('assistido')
    op.drop_table('usuario')
    op.drop_table('conteudo')
    # ### end Alembic commands ###
